'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace facewebservice
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SSPPWebServiceProxyBinding", [Namespace]:="https://webservice.face.gob.es"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SSPPOrganoGestorUnidadTramitadora)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SSPPEstado)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SSPPFicheroAnexo))>  _
    Partial Public Class SSPPWebServiceProxyService
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol

        Private enviarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private anularFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarEstadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarUnidadesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarAdministracionesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarUnidadesPorAdministracionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarListadoFacturasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.waServicioWebFace.My.MySettings.Default.waServicioWebFace_facewebservice_SSPPWebServiceProxyService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event enviarFacturaCompleted As enviarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarFacturaCompleted As consultarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event anularFacturaCompleted As anularFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarEstadosCompleted As consultarEstadosCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarUnidadesCompleted As consultarUnidadesCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarAdministracionesCompleted As consultarAdministracionesCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarUnidadesPorAdministracionCompleted As consultarUnidadesPorAdministracionCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarListadoFacturasCompleted As consultarListadoFacturasCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#enviarFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function enviarFactura(ByVal facturaWS As SSPPFactura) As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoEnviarFactura
            Dim results() As Object = Me.Invoke("enviarFactura", New Object() {facturaWS})
            Return CType(results(0),SSPPResultadoEnviarFactura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub enviarFacturaAsync(ByVal facturaWS As SSPPFactura)
            Me.enviarFacturaAsync(facturaWS, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub enviarFacturaAsync(ByVal facturaWS As SSPPFactura, ByVal userState As Object)
            If (Me.enviarFacturaOperationCompleted Is Nothing) Then
                Me.enviarFacturaOperationCompleted = AddressOf Me.OnenviarFacturaOperationCompleted
            End If
            Me.InvokeAsync("enviarFactura", New Object() {facturaWS}, Me.enviarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnenviarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.enviarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent enviarFacturaCompleted(Me, New enviarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarFactura(ByVal numeroRegistro As String) As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoConsultarFactura
            Dim results() As Object = Me.Invoke("consultarFactura", New Object() {numeroRegistro})
            Return CType(results(0),SSPPResultadoConsultarFactura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarFacturaAsync(ByVal numeroRegistro As String)
            Me.consultarFacturaAsync(numeroRegistro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarFacturaAsync(ByVal numeroRegistro As String, ByVal userState As Object)
            If (Me.consultarFacturaOperationCompleted Is Nothing) Then
                Me.consultarFacturaOperationCompleted = AddressOf Me.OnconsultarFacturaOperationCompleted
            End If
            Me.InvokeAsync("consultarFactura", New Object() {numeroRegistro}, Me.consultarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarFacturaCompleted(Me, New consultarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#anularFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function anularFactura(ByVal numeroRegistro As String, ByVal motivo As String) As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoAnularFactura
            Dim results() As Object = Me.Invoke("anularFactura", New Object() {numeroRegistro, motivo})
            Return CType(results(0),SSPPResultadoAnularFactura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String)
            Me.anularFacturaAsync(numeroRegistro, motivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String, ByVal userState As Object)
            If (Me.anularFacturaOperationCompleted Is Nothing) Then
                Me.anularFacturaOperationCompleted = AddressOf Me.OnanularFacturaOperationCompleted
            End If
            Me.InvokeAsync("anularFactura", New Object() {numeroRegistro, motivo}, Me.anularFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnanularFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.anularFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent anularFacturaCompleted(Me, New anularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarEstados", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarEstados() As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPEstados
            Dim results() As Object = Me.Invoke("consultarEstados", New Object(-1) {})
            Return CType(results(0),SSPPEstados)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarEstadosAsync()
            Me.consultarEstadosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarEstadosAsync(ByVal userState As Object)
            If (Me.consultarEstadosOperationCompleted Is Nothing) Then
                Me.consultarEstadosOperationCompleted = AddressOf Me.OnconsultarEstadosOperationCompleted
            End If
            Me.InvokeAsync("consultarEstados", New Object(-1) {}, Me.consultarEstadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarEstadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarEstadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarEstadosCompleted(Me, New consultarEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidades", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarUnidades() As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoConsultarUnidades
            Dim results() As Object = Me.Invoke("consultarUnidades", New Object(-1) {})
            Return CType(results(0),SSPPResultadoConsultarUnidades)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesAsync()
            Me.consultarUnidadesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesAsync(ByVal userState As Object)
            If (Me.consultarUnidadesOperationCompleted Is Nothing) Then
                Me.consultarUnidadesOperationCompleted = AddressOf Me.OnconsultarUnidadesOperationCompleted
            End If
            Me.InvokeAsync("consultarUnidades", New Object(-1) {}, Me.consultarUnidadesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarUnidadesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarUnidadesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarUnidadesCompleted(Me, New consultarUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministraciones", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarAdministraciones() As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPUnidadDir()
            Dim results() As Object = Me.Invoke("consultarAdministraciones", New Object(-1) {})
            Return CType(results(0),SSPPUnidadDir())
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesAsync()
            Me.consultarAdministracionesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesAsync(ByVal userState As Object)
            If (Me.consultarAdministracionesOperationCompleted Is Nothing) Then
                Me.consultarAdministracionesOperationCompleted = AddressOf Me.OnconsultarAdministracionesOperationCompleted
            End If
            Me.InvokeAsync("consultarAdministraciones", New Object(-1) {}, Me.consultarAdministracionesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarAdministracionesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarAdministracionesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarAdministracionesCompleted(Me, New consultarAdministracionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidadesPorAdministracion", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarUnidadesPorAdministracion(ByVal codigoDir As String) As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoConsultarUnidades
            Dim results() As Object = Me.Invoke("consultarUnidadesPorAdministracion", New Object() {codigoDir})
            Return CType(results(0),SSPPResultadoConsultarUnidades)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String)
            Me.consultarUnidadesPorAdministracionAsync(codigoDir, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String, ByVal userState As Object)
            If (Me.consultarUnidadesPorAdministracionOperationCompleted Is Nothing) Then
                Me.consultarUnidadesPorAdministracionOperationCompleted = AddressOf Me.OnconsultarUnidadesPorAdministracionOperationCompleted
            End If
            Me.InvokeAsync("consultarUnidadesPorAdministracion", New Object() {codigoDir}, Me.consultarUnidadesPorAdministracionOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarUnidadesPorAdministracionOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarUnidadesPorAdministracionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarUnidadesPorAdministracionCompleted(Me, New consultarUnidadesPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarListadoFacturas", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es")>  _
        Public Function consultarListadoFacturas(ByVal listadoFacturas() As Object) As <System.Xml.Serialization.SoapElementAttribute("return")> SSPPResultadoConsultarFactura()
            Dim results() As Object = Me.Invoke("consultarListadoFacturas", New Object() {listadoFacturas})
            Return CType(results(0),SSPPResultadoConsultarFactura())
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarListadoFacturasAsync(ByVal listadoFacturas() As Object)
            Me.consultarListadoFacturasAsync(listadoFacturas, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarListadoFacturasAsync(ByVal listadoFacturas() As Object, ByVal userState As Object)
            If (Me.consultarListadoFacturasOperationCompleted Is Nothing) Then
                Me.consultarListadoFacturasOperationCompleted = AddressOf Me.OnconsultarListadoFacturasOperationCompleted
            End If
            Me.InvokeAsync("consultarListadoFacturas", New Object() {listadoFacturas}, Me.consultarListadoFacturasOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarListadoFacturasOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarListadoFacturasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarListadoFacturasCompleted(Me, New consultarListadoFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPFactura
        
        Private correoField As String
        
        Private fichero_facturaField As SSPPFicheroFactura
        
        Private ficheros_anexosField() As SSPPFicheroAnexo
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fichero_factura() As SSPPFicheroFactura
            Get
                Return Me.fichero_facturaField
            End Get
            Set
                Me.fichero_facturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ficheros_anexos() As SSPPFicheroAnexo()
            Get
                Return Me.ficheros_anexosField
            End Get
            Set
                Me.ficheros_anexosField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPFicheroFactura
        
        Private facturaField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property factura() As String
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPUnidadDir
        
        Private codigo_dirField As String
        
        Private nombreField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codigo_dir() As String
            Get
                Return Me.codigo_dirField
            End Get
            Set
                Me.codigo_dirField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPOrganoGestorUnidadTramitadora
        
        Private organo_gestorField As SSPPUnidadDir
        
        Private unidad_tramitadoraField As SSPPUnidadDir
        
        Private oficina_contableField As SSPPUnidadDir
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property organo_gestor() As SSPPUnidadDir
            Get
                Return Me.organo_gestorField
            End Get
            Set
                Me.organo_gestorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidad_tramitadora() As SSPPUnidadDir
            Get
                Return Me.unidad_tramitadoraField
            End Get
            Set
                Me.unidad_tramitadoraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property oficina_contable() As SSPPUnidadDir
            Get
                Return Me.oficina_contableField
            End Get
            Set
                Me.oficina_contableField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPResultadoConsultarUnidades
        
        Private unidadesField() As SSPPOrganoGestorUnidadTramitadora
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidades() As SSPPOrganoGestorUnidadTramitadora()
            Get
                Return Me.unidadesField
            End Get
            Set
                Me.unidadesField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPEstado
        
        Private nombreField As String
        
        Private codigoField As String
        
        Private descripcionField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPEstados
        
        Private estadosField() As SSPPEstado
        
        '''<comentarios/>
        Public Property estados() As SSPPEstado()
            Get
                Return Me.estadosField
            End Get
            Set
                Me.estadosField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPResultadoAnularFactura
        
        Private numero_registroField As String
        
        Private mensajeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property numero_registro() As String
            Get
                Return Me.numero_registroField
            End Get
            Set
                Me.numero_registroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPResultadoConsultarFacturaEstado
        
        Private codigo_estadoField As String
        
        Private descripcion_estadoField As String
        
        Private motivo_estadoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codigo_estado() As String
            Get
                Return Me.codigo_estadoField
            End Get
            Set
                Me.codigo_estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property descripcion_estado() As String
            Get
                Return Me.descripcion_estadoField
            End Get
            Set
                Me.descripcion_estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property motivo_estado() As String
            Get
                Return Me.motivo_estadoField
            End Get
            Set
                Me.motivo_estadoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPResultadoConsultarFactura
        
        Private numero_registroField As String
        
        Private tramitacionField As SSPPResultadoConsultarFacturaEstado
        
        Private anulacionField As SSPPResultadoConsultarFacturaEstado
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property numero_registro() As String
            Get
                Return Me.numero_registroField
            End Get
            Set
                Me.numero_registroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property tramitacion() As SSPPResultadoConsultarFacturaEstado
            Get
                Return Me.tramitacionField
            End Get
            Set
                Me.tramitacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property anulacion() As SSPPResultadoConsultarFacturaEstado
            Get
                Return Me.anulacionField
            End Get
            Set
                Me.anulacionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPResultadoEnviarFactura
        
        Private codigo_registroField As String
        
        Private organo_gestorField As String
        
        Private unidad_tramitadoraField As String
        
        Private oficina_contableField As String
        
        Private identificador_emisorField As String
        
        Private numero_facturaField As String
        
        Private serie_facturaField As String
        
        Private fecha_recepcionField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codigo_registro() As String
            Get
                Return Me.codigo_registroField
            End Get
            Set
                Me.codigo_registroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property organo_gestor() As String
            Get
                Return Me.organo_gestorField
            End Get
            Set
                Me.organo_gestorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidad_tramitadora() As String
            Get
                Return Me.unidad_tramitadoraField
            End Get
            Set
                Me.unidad_tramitadoraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property oficina_contable() As String
            Get
                Return Me.oficina_contableField
            End Get
            Set
                Me.oficina_contableField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property identificador_emisor() As String
            Get
                Return Me.identificador_emisorField
            End Get
            Set
                Me.identificador_emisorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property numero_factura() As String
            Get
                Return Me.numero_facturaField
            End Get
            Set
                Me.numero_facturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property serie_factura() As String
            Get
                Return Me.serie_facturaField
            End Get
            Set
                Me.serie_facturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fecha_recepcion() As String
            Get
                Return Me.fecha_recepcionField
            End Get
            Set
                Me.fecha_recepcionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class SSPPFicheroAnexo
        
        Private anexoField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property anexo() As String
            Get
                Return Me.anexoField
            End Get
            Set
                Me.anexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub enviarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As enviarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class enviarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoEnviarFactura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoEnviarFactura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As consultarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoConsultarFactura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoConsultarFactura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub anularFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As anularFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class anularFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoAnularFactura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoAnularFactura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarEstadosCompletedEventHandler(ByVal sender As Object, ByVal e As consultarEstadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarEstadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPEstados
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPEstados)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarUnidadesCompletedEventHandler(ByVal sender As Object, ByVal e As consultarUnidadesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarUnidadesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoConsultarUnidades
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoConsultarUnidades)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarAdministracionesCompletedEventHandler(ByVal sender As Object, ByVal e As consultarAdministracionesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarAdministracionesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPUnidadDir()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPUnidadDir())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarUnidadesPorAdministracionCompletedEventHandler(ByVal sender As Object, ByVal e As consultarUnidadesPorAdministracionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarUnidadesPorAdministracionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoConsultarUnidades
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoConsultarUnidades)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub consultarListadoFacturasCompletedEventHandler(ByVal sender As Object, ByVal e As consultarListadoFacturasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarListadoFacturasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SSPPResultadoConsultarFactura()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SSPPResultadoConsultarFactura())
            End Get
        End Property
    End Class
End Namespace
